### ISSUE TITLE
Style not loading on pages apart from the login

### ISSUE THREAD

**Issue by kierenblade** [moemura/AdminLTE.Core#3]
It seems as though the styles fail to load on screens other than the Login screen. This is on a new project with .Net Core 3.1.3 SDK installed

**Console errors:**
![image](https://user-images.githubusercontent.com/19737083/82471613-36654f80-9ac7-11ea-8acd-60b66fdb9d1e.png)

**Home screen:**
![image](https://user-images.githubusercontent.com/19737083/82471493-0e75ec00-9ac7-11ea-85e6-7c5806c6701b.png)

**Comment by moemura** [comment]
Please restore client library first. Libs aren't committed to git.

**Comment by johnjalani** [comment]
@kierenblade Please check this https://github.com/moemura/AdminLTE.Core/issues/1
