### ISSUE TITLE
How to navigate the application

### ISSUE THREAD

**Issue by asif48** [moemura/AdminLTE.Core#4]
Hi...

Sir  a great work that I was searching for...I am very new to asp.net core. I want to ask that how to navigate the application as the application can only render **Login page** even if I change the startup file content. How to access the rest of the pages.

plz help.

**Comment by moemura** [comment]
1. open the project and restore client libraries
2. login using default password in https://github.com/moemura/AdminLTE.Core/blob/master/src/AdminLTE/Data/DataSeed.cs
